# CircuitPython board configuration for ESP32-S3 DevKit
# This is an example configuration file for the ESP32-S3 DevKit

[board]
name = "ESP32-S3 DevKit"
directory_name = "custom_esp32s3_devkit"
mcu = "ESP32-S3"
port_type = "espressif"
idf_target = "esp32s3"

[usb]
vid = "0x303A"
pid = "0x8007"
product = "ESP32-S3 DevKit"
manufacturer = "Espressif"

[flash]
size = "8MB"
mode = "dio"
freq = "80m"

[psram]
size = "8MB"
mode = "octal"
freq = "80m"

[buses]
i2c.scl = "GPIO9"
i2c.sda = "GPIO8"
spi.sck = "GPIO36"
spi.mosi = "GPIO35"
spi.miso = "GPIO37"
uart.rx = "GPIO44"
uart.tx = "GPIO43"

[pins]
# Pin definitions
GPIO0 = "GPIO0"
GPIO1 = "GPIO1"
GPIO2 = "GPIO2"
GPIO3 = "GPIO3"
GPIO4 = "GPIO4"
GPIO5 = "GPIO5"
GPIO6 = "GPIO6"
GPIO7 = "GPIO7"
GPIO8 = "GPIO8"
GPIO9 = "GPIO9"
GPIO10 = "GPIO10"
GPIO11 = "GPIO11"
GPIO12 = "GPIO12"
GPIO13 = "GPIO13"
GPIO14 = "GPIO14"
GPIO15 = "GPIO15"
GPIO16 = "GPIO16"
GPIO17 = "GPIO17"
GPIO18 = "GPIO18"
GPIO19 = "GPIO19"
GPIO20 = "GPIO20"
GPIO21 = "GPIO21"
GPIO35 = "GPIO35"
GPIO36 = "GPIO36"
GPIO37 = "GPIO37"
GPIO38 = "GPIO38"
GPIO39 = "GPIO39"
GPIO40 = "GPIO40"
GPIO41 = "GPIO41"
GPIO42 = "GPIO42"
GPIO43 = "GPIO43"
GPIO44 = "GPIO44"
GPIO45 = "GPIO45"
GPIO46 = "GPIO46"
GPIO47 = "GPIO47"
GPIO48 = "GPIO48"
LED = "GPIO48"

[aliases]
# Pin aliases
TX = "GPIO43"
RX = "GPIO44"
SDA = "GPIO8"
SCL = "GPIO9"
SCK = "GPIO36"
MOSI = "GPIO35"
MISO = "GPIO37"
D0 = "GPIO0"
D1 = "GPIO1"
D2 = "GPIO2"
D3 = "GPIO3"
D4 = "GPIO4"
D5 = "GPIO5"
D6 = "GPIO6"
D7 = "GPIO7"
D8 = "GPIO8"
D9 = "GPIO9"
D10 = "GPIO10"
D11 = "GPIO11"
D12 = "GPIO12"
D13 = "GPIO13"
D14 = "GPIO14"
D15 = "GPIO15"
D16 = "GPIO16"
D17 = "GPIO17"
D18 = "GPIO18"
D19 = "GPIO19"
D20 = "GPIO20"
D21 = "GPIO21"

[sdkconfig]
CONFIG_ESP32S3_SPIRAM_SUPPORT = "y"
CONFIG_SPIRAM_MODE_OCT = "y"
CONFIG_SPIRAM_TYPE_AUTO = "y"
CONFIG_SPIRAM_SIZE = "8388608"
CONFIG_SPIRAM_SPEED_80M = "y"
CONFIG_SPIRAM = "y"
CONFIG_ESP_CONSOLE_USB_SERIAL_JTAG = "y"