USB_VID = 0x2E8A
USB_PID = 0x000A
USB_PRODUCT = "Pico RP2040"
USB_MANUFACTURER = "Raspberry Pi"

CHIP_VARIANT = RP2040
CHIP_FAMILY = rp2

EXTERNAL_FLASH_DEVICES = "W25Q16JVxQ"

CIRCUITPY_USB_CDC = 1
CIRCUITPY_USB_HID = 1
CIRCUITPY_USB_MIDI = 1
CIRCUITPY_USB_MSC = 1
CIRCUITPY_DIGITALIO = 1
CIRCUITPY_ANALOGIO = 1
CIRCUITPY_BUSIO = 1
CIRCUITPY_NEOPIXEL_WRITE = 1
CIRCUITPY_PWMIO = 1
CIRCUITPY_PULSEIO = 1
CIRCUITPY_ROTARYIO = 1
CIRCUITPY_RTC = 1
CIRCUITPY_SDCARDIO = 1
CIRCUITPY_TOUCHIO = 1
CIRCUITPY_USB_HOST = 1
