# Example Raspberry Pi Pico W Configuration
[metadata]
name = "Raspberry Pi Pico W"
vendor = "Raspberry Pi"
url = "https://www.raspberrypi.com"
mcu = "RP2040"

[usb]
vid = "0x2E8A"
pid = "0x0005"
product = "Raspberry Pi Pico W"
manufacturer = "Raspberry Pi"

[build]
cpu = "cortex-m0plus"
fpu = ""
float_abi = ""

[features]
circuitpy_wifi = true
circuitpy_ssl = true

[frozen]
libraries = [
    "Adafruit_CircuitPython_BusDevice",
    "Adafruit_CircuitPython_Requests"
]

[pins]
led = {number = "LED", capabilities = ["digital"]}  # Special "LED" pin for Pico W
button = {number = 23, capabilities = ["digital"]}

[default_interfaces]
uart_rx = 1
uart_tx = 0
i2c_scl = 5
i2c_sda = 4
spi_sck = 18
spi_mosi = 19
spi_miso = 16

[wireless]
wifi_chip = "CYW43439"
wifi_antenna = "chip"