# Example Nordic nRF52840 DK Configuration
[metadata]
name = "nRF52840 DK"
vendor = "Nordic Semiconductor"
url = "https://www.nordicsemi.com"
mcu = "nRF52840"

[usb]
vid = "0x239A"
pid = "0x8029"
product = "nRF52840 DK"
manufacturer = "Nordic Semiconductor"

[build]
cpu = "cortex-m4"
fpu = "fpv4-sp-d16"
float_abi = "hard"

[features]
circuitpy_ble = true
circuitpy_nfc = false

[frozen]
libraries = ["Adafruit_CircuitPython_BLE"]

[pins]
led1 = {number = 13, capabilities = ["digital"]}
led2 = {number = 14, capabilities = ["digital"]}
button1 = {number = 11, capabilities = ["digital"]}
button2 = {number = 12, capabilities = ["digital"]}

[default_interfaces]
uart_rx = 8
uart_tx = 6
i2c_scl = 27
i2c_sda = 26
spi_sck = 47
spi_mosi = 45
spi_miso = 46